Fix and adapt for select_guessers.py

diff --git a/mtensemble/functions b/mtensemble/functions
--- a/mtensemble/functions
+++ b/mtensemble/functions
@@ -1,23 +1,16 @@
-# vim:ft=sh
+# vim:ft=bash
 
-INPUT=/Users/katinska/GramCorr/mtensemble/input
-INPUT_READY=${INPUT}/folds_with_spell
+[ -e .local ] && source .local
+INPUT=${INPUT:-"./input"}
+INPUT_RAW=${INPUT_RAW:-"${INPUT}/00_raw"}               # raw files (copies - if applicable)
+INPUT_PREPROC=${INPUT_PREPROC:-"${INPUT}/01_preproc"}   # preprocessed: sanitised 
+INPUT_FEATURE=${INPUT_FEATURE:-"${INPUT}/10_feature"}   # ready to use
+INPUT_EXPERIMENT=${INPUT_EXPERIMENT:-"${INPUT}/20_experiment"}
+OUTPUT=${OUTPUT:-"./output"}
+OUTPUT_EXPERIMENT=${OUTPUT_EXPERIMENT:-"${OUTPUT}/experiment"}
 
-#INPUT_RAW=${INPUT}/00_raw_last         # raw files (copies - if applicable)
-#INPUT_PREPROC=${INPUT}/01_preproc_last # preprocessed: sanitised
-#INPUT_FEATSET=${INPUT}/features_last
-#INPUT_EXPERIMENT=${INPUT}/input_exp_last
-#OUTPUT=/Users/katinska/GramCorr/mtensemble/output_last
-#OUTPUT_EXPERIMENT=${OUTPUT}/output_exp_last
-
-#INPUT_READY=${INPUT}/new_folds_last
-
-INPUT_RAW=${INPUT}/00_raw         # raw files (copies - if applicable)
-INPUT_PREPROC=${INPUT}/01_preproc # preprocessed: sanitised
-INPUT_FEATSET=${INPUT}/features
-INPUT_EXPERIMENT=${INPUT}/input_exp
-OUTPUT=/Users/katinska/GramCorr/mtensemble/output
-OUTPUT_EXPERIMENT=${OUTPUT}/output_exp
+WEKA_BASE=${WEKA_BASE:-"external/weka/"}
+WEKA_CMD="java -Xmx2g -classpath ${WEKA_BASE}/weka.jar"
 
 #
 # These 'functions' are external to the main script for convenience (testing):
@@ -26,6 +19,9 @@ OUTPUT_EXPERIMENT=${OUTPUT}/output_exp
 
 # Copy original file from I: and gently sanitise data.
 preprocess_file() {
+    set -e
+    set -o pipefail
+
     if [ $# -ne 2 ]
     then
         echo "Usage: ${FUNCNAME[0]} INFILE OUTFILE" >&2
@@ -33,8 +29,8 @@ preprocess_file() {
         return 1
     fi
 
-    INFILE="$1"
-    OUTFILE="$2"
+    local INFILE="$1"
+    local OUTFILE="$2"
     if [ "${INFILE}" -nt "${OUTFILE}" ] 
     then
         sed -e 's/Un\t/Unknown\t/' \
@@ -47,12 +43,23 @@ preprocess_file() {
 }
 
 # Convert .csv files to .arff files (for WEKA).
-convert01() {
-    if [ $# -ne 2 ]
+csv2arff() {
+    if [ $# -lt 2 ]
     then
-        echo "Usage: ${FUNCNAME[0]} FILE.csv OUTFILE.arff" >&2
+        echo "Usage: ${FUNCNAME[0]} FILE.csv OUTFILE.arff [CSVLOADER_EXTRA_ARGS]" >&2
         echo "Convert FILE.csv to FILE.arff" >&2
         return 1
+    fi
+
+    # Set the default to work with a set of 5 Guessers
+    if [ $# -eq 2 ]
+    then
+        local CSVLOADER_EXTRA_ARGS=( \
+            -N "6,8,10,12,14" \
+            -L "6,8,10,12,14:-1,0,1" \
+        )
+    else
+        local CSVLOADER_EXTRA_ARGS=( "${@:3}" )
     fi
 
     # Load csv file & convert to arff
@@ -65,54 +72,43 @@ convert01() {
     # -L <nominal label spec>: 
     #       1,2,4-6:red,green,blue or att1,att2:red,green,blue
     # -B <num>:         The size of the in memory buffer (in rows).
-    INFILE="$1"
-    OUTFILE="$2"
+    local INFILE="$1"
+    local OUTFILE="$2"
     if [ "${INFILE}" -nt "${OUTFILE}" ] 
     then
-        echo "[$(basename "$0")] converting ${INFILE} to ${OUTFILE}" >&2
+        echo "[${FUNCNAME[0]}] ${INFILE} ---> ${OUTFILE}" >&2
+
+        # Weka seems to be exiting with 0 - even in case of failure :(
+        # but there is (usually) output on stderr. So, check for output there...
+        local ERRLOG=$(mktemp)
         ${WEKA_CMD} weka.core.converters.CSVLoader "$INFILE" \
-                -F '\t' -E ',' -M '#' \
-                -S 1,2,4 \
-                -N 5,6,8,10,12,14 \
-                -L "5:0,1" -L "6,8,10,12,14:-1,0,1" \
-                -B 100000 | \
+                -F '\t' -E '#' -M '?' \
+                -S 1,2,4, \
+                -N 5 \
+                -L "5:0,1" \
+                "${CSVLOADER_EXTRA_ARGS[@]}" \
+                -B 1 \
+        2> >(tee -a ${ERRLOG} >&2) \
+        | \
         # Filter unused 'columns' from file AND put GOLD column last
         ${WEKA_CMD} weka.filters.unsupervised.attribute.Reorder \
                 -R 1,3,6-last,5 \
-        > "$OUTFILE" 
+        2> >(tee -a ${ERRLOG} >&2) \
+        > "$OUTFILE"
+        if [[ -s "$ERRLOG" ]]; then
+            echo "FAIL: $ERRLOG is not empty."
+            rm -f $ERRLOG
+            return 1
+        else
+            rm -f $ERRLOG
+        fi
     else
-        echo "[${FUNCNAME[0]}] Doing nothing for ${INFILE}." >&2
+        echo "[${FUNCNAME[0]}] Exists." >&2
     fi
 }
 
 
-#                -F '\t' -E ',' -M '#' \
-#                -S 1,2,4 \
-#                -N 5,6,8,10,12,14 \
-#                -L "5:0,1" -L "6,8,10,12,14:-1,0,1" \
-
-#                -S 1,2,3,5,7,9,11,13,15 \
-#                -N 4,6,8,10,12,14,16 \
-#                -L "4:0,1" -L "6,8,10,12,14,16:-1,0,1" \
-
-#                -S 1,2,4 \
-#                -N 5,6,8,10,12 \
-#                -L "5:0,1" -L "6,8,10,12:-1,0,1" \
-#error_id	type	error_length	suggestion	is_correct	10_gram_is_suggested	10_gram_score	1_gram_is_suggested	1_gram_score	3_gram_is_suggested	3_gram_score	5_gram_is_suggested	5_gram_score	conf_norm_0	conf_norm_1	conf_norm_2	conf_norm_3	delta_0	delta_1	delta_2	delta_3
-#strings: error_id (1), type (2), suggestion (4)
-#nominals: is_correct(5), 10_gram_is_sugg(6), 1_gram_is_sugg(8), 3_gram_sugg(10), 5_gram_sugg(12).
-# what is -L? How to read this notation
-# what is -R?
-
-#error_id	type	error_length	suggestion	is_correct	10_gram_is_suggested	10_gram_score	1_gram_is_suggested	1_gram_score	3_gram_is_suggested	3_gram_score	5_gram_is_suggested	5_gram_score	spellcheker_suggested	spellcheker_score
-
-#expected	error_id	type	error_length	suggestion	is_correct	10_gram_is_suggested	10_gram_score	1_gram_is_suggested	1_gram_score	3_gram_is_suggested	3_gram_score	5_gram_is_suggested	5_gram_score	spellcheker_suggested	spellcheker_score	conf_norm_0	conf_norm_1	conf_norm_2	conf_norm_3	conf_norm_4	delta_0	delta_1	delta_2	delta_3	delta_4
-#strings: 1, 2, 3, 5, 7, 9, 11, 13, 15
-#nominals: 4, 6, 8, 10, 12, 14, 16
-#doesn't work --> generation of arff files (ask Egon).
-
-
-weka-rf() {
+weka_rf() {
     if [ $# -ne 2 ] && [ $# -ne 3 ]
     then
         echo "Usage: ${FUNCNAME[0]} TRAIN_DATA OUTFILE_BASENAME [TEST_DATA]" >&2
